# -*- coding: utf-8 -*-
"""
诊断与错误模型。

不依赖 Flask、pythonnet 或 Siemens DLL。
"""

from __future__ import annotations

from typing import Any

from pydantic import BaseModel, Field

from .enums import DiagnosticSeverity


class Diagnostic(BaseModel):
    """结构化诊断信息。

    用于部署计划、能力验证、编译等各阶段输出统一的诊断结果。
    """

    code: str = Field(..., description="错误代码，如 CAP_UNSUPPORTED_EVENT")
    severity: DiagnosticSeverity = Field(
        default=DiagnosticSeverity.ERROR, description="严重等级"
    )
    phase: str = Field(default="", description="发生阶段")
    object_type: str | None = Field(default=None, description="涉及对象类型")
    object_name: str | None = Field(default=None, description="涉及对象名称")
    message: str = Field(..., description="人类可读的诊断描述")
    details: dict[str, Any] = Field(default_factory=dict, description="附加详情")
    remediation: str | None = Field(
        default=None, description="建议的修复措施"
    )


# ---------------------------------------------------------------------------
# 常用错误码（与方案文档 §17 对齐）
# ---------------------------------------------------------------------------

class DiagnosticCodes:
    """标准诊断错误码。

    不允许硬编码字符串，统一通过此类引用。
    """

    # 能力相关
    CAP_UNSUPPORTED_EVENT = "CAP_UNSUPPORTED_EVENT"
    CAP_UNSUPPORTED_BINDING = "CAP_UNSUPPORTED_BINDING"
    CAP_UNSUPPORTED_SCREEN_ITEM = "CAP_UNSUPPORTED_SCREEN_ITEM"
    CAP_UNSUPPORTED_FEATURE = "CAP_UNSUPPORTED_FEATURE"

    # 依赖相关
    DEP_MISSING_CONNECTION = "DEP_MISSING_CONNECTION"
    DEP_MISSING_CONTROLLER_TAG = "DEP_MISSING_CONTROLLER_TAG"
    DEP_MISSING_TAG_TABLE = "DEP_MISSING_TAG_TABLE"
    DEP_MISSING_SCRIPT = "DEP_MISSING_SCRIPT"

    # Classic XML 相关
    CLASSIC_FRAGMENT_NOT_FOUND = "CLASSIC_FRAGMENT_NOT_FOUND"
    CLASSIC_SCHEMA_MISMATCH = "CLASSIC_SCHEMA_MISMATCH"
    CLASSIC_BROKEN_LINK = "CLASSIC_BROKEN_LINK"
    CLASSIC_DUPLICATE_ID = "CLASSIC_DUPLICATE_ID"

    # Unified 相关
    UNIFIED_TYPE_NOT_FOUND = "UNIFIED_TYPE_NOT_FOUND"
    UNIFIED_EVENT_ENUM_AMBIGUOUS = "UNIFIED_EVENT_ENUM_AMBIGUOUS"
    UNIFIED_PROPERTY_NOT_SUPPORTED = "UNIFIED_PROPERTY_NOT_SUPPORTED"

    # 脚本相关
    SCRIPT_SECURITY_REJECTED = "SCRIPT_SECURITY_REJECTED"
    SCRIPT_SYNTAX_FAILED = "SCRIPT_SYNTAX_FAILED"

    # 导入/编译相关
    IMPORT_TIA_EXCEPTION = "IMPORT_TIA_EXCEPTION"
    IMPORT_OPTIONS_RESOLVE_FAILED = "IMPORT_OPTIONS_RESOLVE_FAILED"
    IMPORT_OPTIONS_UPSERT_FALLBACK = "IMPORT_OPTIONS_UPSERT_FALLBACK"
    COMPILE_ERROR = "COMPILE_ERROR"
    COMPILE_WARNING = "COMPILE_WARNING"

    # 验证相关
    VERIFY_TAG_MISSING = "VERIFY_TAG_MISSING"
    VERIFY_EVENT_MISSING = "VERIFY_EVENT_MISSING"
    VERIFY_BINDING_MISSING = "VERIFY_BINDING_MISSING"
    VERIFY_SCRIPT_MISSING = "VERIFY_SCRIPT_MISSING"
    VERIFY_SCREEN_MISSING = "VERIFY_SCREEN_MISSING"

    # 通用
    IR_VALIDATION_ERROR = "IR_VALIDATION_ERROR"
    LEGACY_ADAPTER_WARNING = "LEGACY_ADAPTER_WARNING"
    UNKNOWN_ERROR = "UNKNOWN_ERROR"

    # 部署状态机
    TARGET_FAMILY_AMBIGUOUS = "TARGET_FAMILY_AMBIGUOUS"
    TIA_NOT_CONNECTED = "TIA_NOT_CONNECTED"
    DEPLOY_BLOCKED = "DEPLOY_BLOCKED"
    DEPLOY_FAILED = "DEPLOY_FAILED"
    VERIFY_FAILED = "VERIFY_FAILED"

    # 编译相关
    COMPILE_SUCCESS = "COMPILE_SUCCESS"
    COMPILE_FAILED = "COMPILE_FAILED"

    # 模板引用泄漏
    CLASSIC_TEMPLATE_TAG_REFERENCE_LEAK = "CLASSIC_TEMPLATE_TAG_REFERENCE_LEAK"

    # V3.2 新增: Tag 导入与引用诊断码
    DEFAULT_TAG_TABLE_NOT_FOUND = "DEFAULT_TAG_TABLE_NOT_FOUND"
    CLASSIC_TAG_XML_KIND_UNKNOWN = "CLASSIC_TAG_XML_KIND_UNKNOWN"
    TAG_MAPPING_MISSING = "TAG_MAPPING_MISSING"
    TAG_XML_TEMPLATE_REFERENCE_REMAINS = "TAG_XML_TEMPLATE_REFERENCE_REMAINS"
    SCREEN_TEMPLATE_TAG_REFERENCE_REMAINS = "SCREEN_TEMPLATE_TAG_REFERENCE_REMAINS"
    SCREEN_TAG_REFERENCE_NOT_DEFINED = "SCREEN_TAG_REFERENCE_NOT_DEFINED"
    IMPORTED_TAG_NOT_FOUND = "IMPORTED_TAG_NOT_FOUND"
    BUTTON_EVENT_TAG_MISMATCH = "BUTTON_EVENT_TAG_MISMATCH"
    DYNAMIZATION_TAG_MISMATCH = "DYNAMIZATION_TAG_MISMATCH"
    REVERSE_EXPORT_TEMPLATE_REFERENCE_REMAINS = "REVERSE_EXPORT_TEMPLATE_REFERENCE_REMAINS"

    # 文本列表
    TEXT_LIST_MISSING = "TEXT_LIST_MISSING"
    SYMBOLIC_IO_DOWNGRADED = "SYMBOLIC_IO_DOWNGRADED"

    # 运行时契约
    CONTRACT_MISSING_TYPE = "CONTRACT_MISSING_TYPE"
    CONTRACT_MISSING_METHOD = "CONTRACT_MISSING_METHOD"
    CONTRACT_MISSING_PROPERTY = "CONTRACT_MISSING_PROPERTY"
    CONTRACT_MISSING_EVENT = "CONTRACT_MISSING_EVENT"
    CONTRACT_DYNAMIZATION_UNSUPPORTED = "CONTRACT_DYNAMIZATION_UNSUPPORTED"

    # V4.0 新增: 模板绑定校验
    IR_BUTTON_BINDING_MISSING = "IR_BUTTON_BINDING_MISSING"
    IR_INDICATOR_BINDING_MISSING = "IR_INDICATOR_BINDING_MISSING"
    IR_TAG_REFERENCE_MISSING = "IR_TAG_REFERENCE_MISSING"

    # V4.0 新增: 模板阶段错误码
    TEMPLATE_XML_PARSE_FAILED = "TEMPLATE_XML_PARSE_FAILED"
    TEMPLATE_NO_BUTTON_PROTOTYPE = "TEMPLATE_NO_BUTTON_PROTOTYPE"
    TEMPLATE_NO_INDICATOR_PROTOTYPE = "TEMPLATE_NO_INDICATOR_PROTOTYPE"
    TEMPLATE_PROTOTYPE_TAG_NOT_FOUND = "TEMPLATE_PROTOTYPE_TAG_NOT_FOUND"
    TEMPLATE_PLACEHOLDER_REMAINING = "TEMPLATE_PLACEHOLDER_REMAINING"
    TEMPLATE_EVENT_TAG_REPLACE_FAILED = "TEMPLATE_EVENT_TAG_REPLACE_FAILED"
    TEMPLATE_DYNAMIC_TAG_REPLACE_FAILED = "TEMPLATE_DYNAMIC_TAG_REPLACE_FAILED"

    # V4.0 新增: 导入阶段错误码
    TAG_IMPORT_FAILED = "TAG_IMPORT_FAILED"
    SCREEN_XML_PRECHECK_FAILED = "SCREEN_XML_PRECHECK_FAILED"
    SCREEN_IMPORT_FAILED = "SCREEN_IMPORT_FAILED"
    COMPILE_FAILED = "COMPILE_FAILED"
    VERIFY_SCREEN_ITEM_MISSING = "VERIFY_SCREEN_ITEM_MISSING"

    # V4.2 新增: Family Unknown 阻断
    HMI_FAMILY_UNKNOWN = "HMI_FAMILY_UNKNOWN"
    # V4.2 新增: .NET 反射 — Create 方法缺失
    TAG_CREATE_METHOD_NOT_FOUND = "TAG_CREATE_METHOD_NOT_FOUND"
    # V4.2 新增: Classic XML 导入目标不可用
    CLASSIC_TAG_IMPORT_TARGET_NOT_FOUND = "CLASSIC_TAG_IMPORT_TARGET_NOT_FOUND"
    # V4.2 新增: Unified Tags 无 Create 方法
    UNIFIED_TAG_CREATE_METHOD_NOT_FOUND = "UNIFIED_TAG_CREATE_METHOD_NOT_FOUND"

    # V4.2 新增: TagComposition Import 策略
    TAG_XML_IMPORT_FAILED = "TAG_XML_IMPORT_FAILED"
    TAG_IMPORT_METHOD_NOT_FOUND = "TAG_IMPORT_METHOD_NOT_FOUND"
    IMPORT_OPTION_PARAMETER_NOT_FOUND = "IMPORT_OPTION_PARAMETER_NOT_FOUND"
